<?php

function econ_pages_menu() {
  $items['news-events'] = array(
      'page callback' => 'econ_pages_news_events_page',
      'page arguments' => array('20'),
      'access arguments' => array('access content'), 
      'file' => 'pages/news-events.inc', 
      'type' => MENU_LOCAL_TASK,
    );
  $items['news-events/news'] = array(
      'page callback' => 'econ_pages_news_page',
      'page arguments' => array('20'),
      'access arguments' => array('access content'), 
      'file' => 'pages/news.inc', 
      'type' => MENU_LOCAL_TASK,
    );  
  $items['news-events/events'] = array(
    'page callback' => 'econ_pages_events_page',
    'page arguments' => array('20'),
    'access arguments' => array('access content'), 
    'file' => 'pages/events.inc', 
    'type' => MENU_LOCAL_TASK,
  );  
  $items['people'] = array(
    'page callback' => 'econ_pages_people_abc_page',
    'page arguments' => array('20'),
    'access arguments' => array('access content'), 
    'file' => 'pages/people.inc', 
    'type' => MENU_LOCAL_TASK,
    'menu_name' => 'menu-econ-mainmenu'
  );  
  $items['people/%'] = array(
    'page callback' => 'econ_pages_people_structure_page',
    'page arguments' => array('20'),
    'access arguments' => array('access content'), 
    'file' => 'pages/people.inc', 
    'type' => MENU_LOCAL_TASK,
  );  
  return $items;
}

function econ_pages_block_info() {
  $blocks = array();
  $blocks['menu-aside'] = array(
    'info' => t('Боковое меню'),
  );
  $blocks['news-filter'] = array(
    'info' => t('Фильтр новостей'),
  );
  $blocks['events-filter'] = array(
    'info' => t('Фильтр событий'),
  );
  $blocks['events-last'] = array(
    'info' => t('Последние события'),
  );
  $blocks['news-search'] = array(
    'info' => t('Поиск по новостям и событиям'),
  );
  $blocks['adverts-last'] = array(
    'info' => t('Последние объявления'),
  );
  $blocks['adverts-last-slider'] = array(
    'info' => t('Последние объявления (слайдер)'),
  );
  $blocks['news-last'] = array(
    'info' => t('Последние новости'),
  );
  $blocks['intro'] = array(
    'info' => t('Слайдер на главной'),
  );
  return $blocks;
}

function econ_pages_block_view($delta='') {
  $block = array();
 
  switch($delta) {
    case 'menu-aside' :
      $block['content'] = _econ_pages_menu_block_view('menu_block');
    break;
    case 'news-filter' :
      module_load_include('inc', 'econ_pages', 'blocks/filters');
      $block['content'] = _econ_pages_news_filter();
    break;

    case 'events-filter' :
      module_load_include('inc', 'econ_pages', 'blocks/filters');
      $block['content'] = _econ_pages_events_filter();
    break;

    case 'events-last' :
      module_load_include('inc', 'econ_pages', 'blocks/events');
      $block['content'] = _econ_pages_events_last_block_view();
    break;

    case 'news-search' :
      module_load_include('inc', 'econ_pages', 'blocks/search');
      $block['content'] = _econ_pages_search_block_view();
    break;
    case 'adverts-last' :
      module_load_include('inc', 'econ_pages', 'blocks/adverts');
      $block['content'] = _econ_pages_adverts_last_block_view();
    break;
    case 'adverts-last-slider' :
      module_load_include('inc', 'econ_pages', 'blocks/adverts');
      $block['content'] = _econ_pages_adverts_last_slider_block_view();
    break;
    case 'news-last' :
      module_load_include('inc', 'econ_pages', 'blocks/news');
      $block['content'] = _econ_pages_news_last_block_view();
    break;
    case 'intro' :
      module_load_include('inc', 'econ_pages', 'blocks/intro');
      $block['content'] = _econ_pages_intro_block_view();
    break;
  }
 
  return $block;
}

function econ_pages_submenu_tree_all_data($mlid, $menu = 'menu-econ-mainmenu') {
  $tree = menu_tree_all_data($menu);
  $tree = i18n_menu_localize_tree($tree);

  foreach ($tree as $branch) {
    if ($branch['link']['mlid'] == $mlid and count($branch['below'])) {

      return array_values($branch['below']);
    }
  }
  return array_values($tree);
}
function _econ_pages_get_current_mlid() {
  global $language; 
  $mlid = array();
  $q = current_path();
  $menu_info = db_select('menu_links' , 'ml')
    ->condition('ml.link_path' , $q)
    ->condition('ml.menu_name', 'menu-econ-mainmenu')
    ->condition('ml.language', array("und", $language->language), "IN")
    ->fields('ml', array('mlid', 'plid'))
    ->execute()
    ->fetchAll();

  foreach($menu_info as $key => $value) {
    $mlid[] = $menu_info[$key]->mlid;
  }

  if (count($mlid)) {
    return $mlid[0];
  } else {
    // не в меню 
    return 0;
  }
}
function _econ_pages_get_menu() {
  
  $mainmenu = array();
  // не могу использовать нормальну ф-цию menu_build_tree, так как есть баг (если дважды ее вызывать)
  // see https://www.drupal.org/node/1697570  
  // menu_tree_all_data возвращает hidden ссылки, нужно проверять 

  $current_mlid = _econ_pages_get_current_mlid();

  $parents = token_menu_link_load_all_parents($current_mlid); 

  if (count($parents) == 0) {
      //1 уровень 

      return $mainmenu = econ_pages_submenu_tree_all_data(0, 'menu-econ-mainmenu');
  }
  if (count($parents) >= 1) {
      //2 уровень
      $keys = array_keys($parents) ;
      return $mainmenu = econ_pages_submenu_tree_all_data($keys[0], 'menu-econ-mainmenu');
  } 
  return $mainmenu;
}
// todo заменить на parents
function _econ_pages_get_active_mlids() {
  $current_mlid = _econ_pages_get_current_mlid();

  $parents = token_menu_link_load_all_parents($current_mlid); 

  $active = array_keys($parents) ;
  $active[] = $current_mlid;
  return $active;
}

function _econ_pages_menu_block_view($template) {

  $menu =  _econ_pages_get_menu() ;  

  $active = _econ_pages_get_active_mlids();
  
	return theme_render_template(drupal_get_path('module', 'econ_pages')."/templates/".$template.".tpl.php", 
    array("menu"=>$menu, "active_trail" => $active));
}

function _econ_pages_render_featured($i) {
  // i - порядковый номер пункта меню

  switch($i) {
    case 1:
      $delta = 2;
    break;
    case 2:
      $delta = 3;
    break;
    case 3:
      $delta = 4;
    break;
    case 4:
      $delta = 5;
    break;
    case 5:
      $delta = 6;
    break;
    case 6:
      $delta = 7;
    break;
    default:
      $delta = 2;
    break;
  }
  $block = module_invoke('block', 'block_view', $delta);
  return render($block['content']);
}
/** для адресов вида people/centri/ **/
function _econ_pages_get_people_path() {
  $paths = array("1"=>"administracia", "2"=>"kafedri", "3"=>"centri");
  return $paths; 
} 
function _econ_pages_remove_hidden(&$menu) {
  foreach ($menu as $k=>$m) {
    if ($m['link']['hidden']==1) {
      unset($menu[$k]);
    }
   }

}



